version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - redis
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

  redis:
    image: redis:latest
    networks:
      - backend

  python_app:
    build: ./python_app
    depends_on:
      - redis
      - mangodb
      - mangodb1
    ports:
      - "5000:5000"
    networks:
      - backend
  
  mangodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  mangodb1:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - backend